name: Test Production Tag

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  prodTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
    - uses: actions/checkout@v6
      with:
        path: go/src/github.com/${{ github.repository }}
        fetch-depth: 0
      
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14' 

    - name: Test With Traefik
      run: sh ./test/test.sh production

    - name: Upload log artifacts
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: logs
        if-no-files-found: error
        path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}/test/output/*
        retention-days: 30
